all:
	# python3 formulaone2.py aus
	# python3 formulaone2.py esp
	# python3 formulaone2.py mnc
	# python3 formulaone2.py bel
	# python3 formulaone2.py ita
	# python3 formulaone2.py hun
	# python3 formulaone2.py usa
	# python3 formulaone2.py jpn
	# python3 formulaone2.py cnd
	# python3 formulaone2.py brz

	# python3 formulaone.py aus --plot
	# python3 formulaone.py esp --plot
	# python3 formulaone.py mnc --plot
	# python3 formulaone.py bel --plot
	# python3 formulaone.py ita --plot
	# python3 formulaone.py hun --plot
	# python3 formulaone.py usa --plot
	# python3 formulaone.py jpn --plot
	# python3 formulaone.py cnd --plot
	# python3 formulaone.py brz --plot

	# python3 formulaone3.py aus
	# python3 formulaone3.py esp
	# python3 formulaone3.py mnc
	# python3 formulaone3.py bel
	# python3 formulaone3.py ita
	# python3 formulaone3.py hun
	# python3 formulaone3.py usa
	# python3 formulaone3.py jpn
	# python3 formulaone3.py cnd
	# python3 formulaone3.py brz

	# python3 formulaone4.py aus --plot
	# python3 formulaone4.py esp --plot
	# python3 formulaone4.py mnc --plot
	# python3 formulaone4.py bel --plot
	# python3 formulaone4.py ita --plot
	# python3 formulaone4.py hun --plot
	# python3 formulaone4.py usa --plot
	# python3 formulaone4.py jpn --plot
	# python3 formulaone4.py cnd --plot
	# python3 formulaone4.py brz --plot

	python3 formulaone5.py aus
	python3 formulaone5.py esp
	python3 formulaone5.py mnc
	python3 formulaone5.py bel
	python3 formulaone5.py ita
	python3 formulaone5.py hun
	python3 formulaone5.py usa
	python3 formulaone5.py jpn
	python3 formulaone5.py cnd
	python3 formulaone5.py brz
